name: 'Doppler env'
description: 'An action for injecting Doppler environment variables into eas based on profile'
inputs:
  profile:
    description: 'expo profile to use for build'
    required: true
    default: 'production'
runs:
  using: 'node16'
  main: 'dist/index.js'